### ISSUE TITLE
Uncaught TypeError: repo.__isPathIgnored__Original is not a function

### ISSUE THREAD

**Issue by averrin** [jacquescrocker/atom-ignore#2]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0-beta4
**System**: KDE neon
**Thrown From**: [atom-ignore](https://github.com/jacquescrocker/atom-ignore) package, v0.2.0

### Stack Trace

Uncaught TypeError: repo.__isPathIgnored__Original is not a function

```
At /home/user/.atom/packages/atom-ignore/lib/atom-ignore.js:35

TypeError: repo.__isPathIgnored__Original is not a function
    at GitRepository.isPathIgnoredWithAtomIgnoreFile [as isPathIgnored] (/home/user/.atom/packages/atom-ignore/lib/atom-ignore.js:35:21)
    at Directory.module.exports.Directory.updateStatus (/usr/share/atom-beta/resources/app.asar/node_modules/tree-view/lib/directory.js:130:16)
    at /usr/share/atom-beta/resources/app.asar/node_modules/tree-view/lib/directory.js:118:24
    at doNTCallback0 (node.js:443:9)
    at process._tickCallback (node.js:372:13)
```

### Commands

```
     -0:10.2.0 project-switcher2:toggle (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:10.2.0 blur (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
  3x -0:08.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:06.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:05.6.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:04.3.0 project-switcher2:toggle (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-base16-tomorrow-dark-theme.theme-accents-ui)
     -0:02.1.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:01.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.3.0 blur (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "web-browser",
      "tool-bar-main",
      "spell-check",
      "seti-icons",
      "atom-color-highlight",
      "tool-bar",
      "toolbar-basic",
      "background-tips",
      "image-view",
      "language-csharp",
      "deprecation-cop",
      "symbols-view",
      "symbols-tree-view",
      "vim-mode",
      "color-tabs-regex",
      "vim-shift-movers",
      "about",
      "archive-view",
      "autoflow",
      "dev-live-reload",
      "encoding-selector",
      "language-c",
      "language-make",
      "language-objective-c",
      "language-php",
      "language-ruby",
      "language-ruby-on-rails",
      "link",
      "styleguide",
      "tidy-tabs",
      "tab-to-escape",
      "godef",
      "linter-golinter",
      "glow",
      "go-debug",
      "linter-eslint",
      "linter-jscs"
    ],
    "excludeVcsIgnoredPaths": false,
    "themes": [
      "accents-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "atom-ignore": {}
}
```

### Installed Packages

```coffee
# User
MagicPython, v0.5.11
accents-ui, v1.2.0
api-docs, vundefined
atom-beautify, v0.29.7
atom-ctags, v4.5.2
atom-hide-tabs, v0.2.1
atom-ignore, v0.2.0
atom-jinja2, v0.5.0
atomic-sync, v0.6.4
autocomplete-go, v1.1.0
autocomplete-paths, v1.0.2
autocomplete-python, v1.7.3
build, v0.64.0
build-gulp, v0.9.0
builder-go, v1.0.0
busy, v0.5.0
close-other-tabs, v0.1.0
code-stats-atom, v1.2.0
color-picker, v2.1.1
colorful-cursor, v0.3.1
console-log, v1.3.3
editorconfig, v1.4.1
emmet, v2.4.3
environment, v1.2.0
file-icons, v1.7.13
git-change-marker, v0.9.0
git-hide, v0.1.2
go-config, v1.1.4
go-find-references, v1.2.3
go-get, v1.0.3
go-plus, v4.1.0
gofmt, v1.1.6
gometalinter-linter, v1.1.0
gorename, v1.0.2
javascript-snippets, v1.2.1
language-babel, v2.25.1
language-diff, v0.4.0
language-lua, v0.9.4
less-than-slash, v0.13.0
linter, v1.11.4
linter-govet, v0.1.5
linter-jshint, v2.1.0
linter-pep8, v1.3.0
linter-pylama, v0.2.9
merge-conflicts, v1.4.3
minimap, v4.24.3
minimap-bookmarks, v0.3.1
minimap-cursorline, v0.1.0
minimap-find-and-replace, v4.5.1
minimap-git-diff, v4.3.1
minimap-highlight-selected, v4.4.0
minimap-pigments, v0.2.1
navigator-godef, v1.0.3
nerd-treeview, v0.4.2
pigments, v0.29.1
project-switcher2, v1.3.1
python-tools, v0.6.7
remember-file-positions, v0.2.2
swackets, v0.10.0
sync-settings, v0.7.2
tester-go, v1.0.4
time-status, v1.1.2
tree-view-search-bar, v0.0.1
underline-trailing-whitespace, v1.4.0
vim-mode-plus, v0.43.0
vim-mode-plus-move-to-symbols, v0.1.5
vim-mode-plus-subword-movement, v0.2.2
wakatime, v6.0.2

# Dev
No dev packages
```

**Comment by jacquescrocker** [comment]
thanks for the heads up! ill look into this

**Comment by artdevjs** [comment]
any updates with this issue?

**Comment by 62316e** [comment]
Projects looks dead.

**Comment by jacquescrocker** [comment]
@62316e I ended up just switching to Visual Studio Code. They have a per project workspace-settings that solves the problem beautifully.

Using Atom for 2yrs was a continual nightmare in tracking which files I want included, and which ones I didnt (for search and quick find). Glad to be done with that

**Comment by 62316e** [comment]
Sounds reasonable. 

Good that you found solution for yourself but it looks like ppl still find this module useful. 

Can you at least mark it deprecated?

**Comment by jacquescrocker** [comment]
@62316e sure, I updated the description in the repo. Any other place I should mark it? Happy to make any suggested changes.

Thanks for the heads up

**Comment by DogsForArms** [comment]
This is preventing me from using it :{

**Comment by joernroeder** [comment]
same here. any improvements?

**Comment by Alexnder** [comment]
It's still the same.

**Comment by MartinWirth** [comment]
Bug still not fixed.

**Comment by jacquescrocker** [comment]
I switched to VSCode a long time ago. Highly recommended.

I'll mark this repo as dead.
